### ISSUE TITLE
Update needed in the UbuCon Asia Documentation

### ISSUE THREAD

**Issue by PratikforCoding** [ubucon-asia/docs.ubucon.asia#4]
Few things need to be fixed:
1. The link for the telegram participants chat and the organizer open discussion are same, this should be different I guess.
2. The documentation can be improved with better sentences.
3. The Organizer page at https://docs.ubucon.asia/organizer/ needs to be written I can help with that if proper instruction provided.
4. Some typos exist that can be fixed easily.
5. I think the roles descriptions are still left to be written , https://docs.ubucon.asia/organizer/teams_roles/

**Comment by Saptarshi2002** [comment]
> 1. The link for the telegram participants chat and the organizer open discussion are same, this should be different I guess.

https://t.me/UbuConAsia

This is the correct link.

**Comment by PratikforCoding** [comment]
Thanks @Saptarshi2002 !! Let me fix this.

**Comment by sukso96100** [comment]
Seems like this issue is now stale. I'm closing this issue for now, but feel free to re-open later if you want
